/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/bottle.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Bottle(props) {
  const { nodes, materials } = useGLTF('/models/bottle2.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bottle.geometry} material={materials.Glass} rotation={[-Math.PI, 0.919, -Math.PI]} scale={0.958} />
      <mesh geometry={nodes.Liquid.geometry} material={materials.Liquid} rotation={[-Math.PI, 0.919, -Math.PI]} scale={1.01} />
      <group rotation={[-Math.PI, 0.919, -Math.PI]}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials['Cap-top']} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Cap-bottom']} />
      </group>
      <mesh geometry={nodes.label.geometry} material={materials.Label} rotation={[-Math.PI, 0.919, -Math.PI]} scale={0.97} />
    </group>
  )
}

useGLTF.preload('/models/bottle2.gltf')
